# Generated by Django 5.0.3 on 2024-04-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_alter_profile_about_profession_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_profession',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_profession',
            field=models.ManyToManyField(blank=True, to='landingpage.stringvalue'),
        ),
    ]
