# Generated by Django 5.0.3 on 2024-07-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_remove_profile_cover_profession_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StringValue',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_profession',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
