# Generated by Django 5.0.3 on 2024-07-10 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_delete_stringvalue_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facts',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.factdetails'),
        ),
        migrations.AddField(
            model_name='factdetails',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.facts'),
        ),
    ]
