# Generated by Django 5.0.3 on 2024-07-10 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_factdetails_facts_website_alter_profile_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facts',
        ),
        migrations.AddField(
            model_name='facts',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='landingpage.profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FactDetails',
        ),
    ]
