# Generated by Django 5.0.3 on 2024-07-10 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_remove_profile_facts_facts_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact', to='landingpage.profile'),
        ),
    ]
