# Generated by Django 5.0.3 on 2024-07-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_alter_facts_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facts',
            options={'verbose_name_plural': 'Fact'},
        ),
        migrations.RemoveField(
            model_name='facts',
            name='title',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='value',
        ),
        migrations.AddField(
            model_name='facts',
            name='number_happy_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facts',
            name='number_hard_workers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facts',
            name='number_hours_of_support',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facts',
            name='number_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facts',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.profile'),
        ),
    ]
