# Generated by Django 5.0.3 on 2024-07-15 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_alter_profile_address_alter_profile_cover_profession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facts',
            options={'verbose_name_plural': 'Facts'},
        ),
        migrations.AddField(
            model_name='facts',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300, null=True)),
                ('number_happy_clients', models.IntegerField(default=0)),
                ('number_projects', models.IntegerField(default=0)),
                ('number_hours_of_support', models.IntegerField(default=0)),
                ('number_hard_workers', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.profile')),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('percent', models.IntegerField(default=0)),
                ('skill', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.skills')),
            ],
        ),
    ]
