# Generated by Django 5.0.3 on 2024-07-15 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0012_alter_facts_options_facts_description_skills_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='number_happy_clients',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='number_hard_workers',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='number_hours_of_support',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='number_projects',
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_skills', to='landingpage.skills'),
        ),
    ]
