# Generated by Django 5.0.3 on 2024-07-15 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0013_remove_skills_number_happy_clients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(null=True)),
                ('institute', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(max_length=50, null=True)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.profile')),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
    ]
