# Generated by Django 5.0.3 on 2024-07-15 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0014_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(null=True)),
                ('company', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30, null=True)),
                ('responsibilities', models.TextField(max_length=200, null=True)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.profile')),
            ],
            options={
                'verbose_name_plural': 'Experience',
            },
        ),
    ]
