# Generated by Django 5.0.3 on 2024-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0015_education_location_alter_education_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
