# Generated by Django 5.0.3 on 2024-07-16 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0019_alter_resume_options_alter_resume_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_services', to='landingpage.services'),
        ),
    ]
