# Generated by Django 5.0.3 on 2024-07-16 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0021_testimonials_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='Testimonial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_testimonials', to='landingpage.testimonials'),
        ),
    ]
