# Generated by Django 5.0.3 on 2024-07-16 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0022_alter_testimonial_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='name',
            new_name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='Testimonial',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.testimonials'),
        ),
    ]
