# Generated by Django 5.0.3 on 2024-07-25 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0026_remove_education_profile_education_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('subject', models.CharField(max_length=30, null=True)),
                ('message', models.TextField(max_length=300, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landingpage.profile')),
            ],
            options={
                'verbose_name_plural': 'ContactForm',
            },
        ),
    ]
