# Generated by Django 5.0.3 on 2024-07-25 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0027_contact_address_contact_email_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('subject', models.CharField(max_length=30, null=True)),
                ('message', models.TextField(max_length=300, null=True)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='landingpage.profile')),
            ],
            options={
                'verbose_name_plural': 'Message',
            },
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
