# Generated by Django 5.0.3 on 2024-07-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0028_message_delete_contactform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
