# Generated by Django 5.0.3 on 2024-07-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0029_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.profile', unique=True),
        ),
    ]
