# Generated by Django 5.0.3 on 2024-07-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0031_alter_testimonials_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.profile', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.AlterField(
            model_name='facts',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.profile'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.profile'),
        ),
        migrations.AlterField(
            model_name='services',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.profile'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.profile'),
        ),
    ]
