# Generated by Django 5.0.3 on 2024-07-26 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0032_websiteprofile_delete_website_alter_facts_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landingpage.profile'),
        ),
    ]
