# Generated by Django 5.0.3 on 2024-07-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0033_alter_websiteprofile_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteprofile',
            options={'verbose_name_plural': 'Website Profile'},
        ),
    ]
