# Generated by Django 5.0.3 on 2024-08-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0035_alter_profile_about_profession_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facts',
            name='description',
        ),
    ]
