# Generated by Django 5.0.3 on 2024-08-02 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0036_remove_facts_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortFolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='landingpage.profile', unique=True)),
                ('portfolio_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.portfoliocategory')),
            ],
        ),
    ]
