# Generated by Django 5.0.3 on 2024-08-02 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0037_portfoliocategory_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'verbose_name_plural': 'Portfolio Categories'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_category',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='landingpage.profile'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=30, null=True)),
                ('link', models.URLField(blank=True, max_length=30, null=True)),
                ('portfolio_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landingpage.portfoliocategory')),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_portfolio_items', to='landingpage.portfolio')),
            ],
        ),
    ]
