# Generated by Django 5.0.3 on 2024-08-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0038_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
    ]
