# Generated by Django 5.0.3 on 2024-08-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0039_alter_portfolio_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='service',
            new_name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
