# Generated by Django 5.0.3 on 2024-08-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0040_rename_service_portfolioitem_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facts',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
