# Generated by Django 5.0.3 on 2024-08-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0041_facts_description_alter_portfolioitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
