# Generated by Django 5.0.3 on 2024-08-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0043_remove_skills_order_skill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(auto_created=True),
        ),
    ]
