# Generated by Django 5.0.3 on 2024-08-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0044_alter_skill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
