# Generated by Django 5.0.3 on 2024-08-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0045_alter_skill_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='profile',
            new_name='resume',
        ),
    ]
