# Generated by Django 5.0.3 on 2024-08-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0046_rename_profile_experience_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_client',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_url',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
