# Generated by Django 5.0.3 on 2024-08-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0047_portfolioitem_photos_portfolioitem_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
