# Generated by Django 5.0.3 on 2024-08-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0048_alter_portfolioitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
