# Generated by Django 5.0.3 on 2024-08-16 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0050_rename_skills_skillhead_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='skill_head',
        ),
    ]
