# Generated by Django 5.0.3 on 2024-08-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0051_rename_skill_skill_skill_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
