# Generated by Django 5.0.3 on 2025-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0052_alter_education_level_alter_experience_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
